In [2]:
import os
import pandas as pd
import random

In [3]:
#path to the dataset
dataset_path = "data/flower_images"

data = []

In [14]:
for label in os.listdir(dataset_path):
    class_folder = os.path.join(dataset_path, label)

    for image_name in os.listdir(class_folder):
        image_path = os.path.join(class_folder, image_name)
        data.append([image_path, label])

In [18]:
data[0:3]

[['data/flower_images\\Lilly\\.ipynb_checkpoints', 'Lilly'],
 ['data/flower_images\\Lilly\\00048a5c76.jpg', 'Lilly'],
 ['data/flower_images\\Lilly\\001ff6644e.jpg', 'Lilly']]

In [19]:
#creat the data frame
df = pd.DataFrame(data, columns = ["image_path", "label"])

In [20]:
df.head()

                                    image_path  label
0  data/flower_images\Lilly\.ipynb_checkpoints  Lilly
1      data/flower_images\Lilly\00048a5c76.jpg  Lilly
2      data/flower_images\Lilly\001ff6644e.jpg  Lilly
3      data/flower_images\Lilly\001ff6656j.jpg  Lilly
4      data/flower_images\Lilly\00973ad1b1.jpg  Lilly

In [23]:
df = df.drop(0)

In [24]:
df.head()

                                image_path  label
1  data/flower_images\Lilly\00048a5c76.jpg  Lilly
2  data/flower_images\Lilly\001ff6644e.jpg  Lilly
3  data/flower_images\Lilly\001ff6656j.jpg  Lilly
4  data/flower_images\Lilly\00973ad1b1.jpg  Lilly
5  data/flower_images\Lilly\00a7d512d6.jpg  Lilly

In [25]:
#shuffle the dataset
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

In [28]:
split_index = len(df) // 1.2
split_index

3333.0