In [1]:
import os
import pandas as pd
import random

In [2]:
#path to the dataset
dataset_path = "data/flower_images"

data = []

In [3]:
for label in os.listdir(dataset_path):
    class_folder = os.path.join(dataset_path, label)

    for image_name in os.listdir(class_folder):
        image_path = os.path.join(class_folder, image_name)
        data.append([image_path, label])

In [4]:
data[0:3]

[['data/flower_images\\Lilly\\.ipynb_checkpoints', 'Lilly'],
 ['data/flower_images\\Lilly\\00048a5c76.jpg', 'Lilly'],
 ['data/flower_images\\Lilly\\001ff6644e.jpg', 'Lilly']]

In [5]:
#creat the data frame
df = pd.DataFrame(data, columns = ["image_path", "label"])

In [44]:
label_map = {label : idx for idx, label in enumerate(df["label"].unique())}
df["label"] = df["label"].map(label_map)

In [6]:
df = df.drop(0)

In [7]:
df.head()

                                image_path  label
1  data/flower_images\Lilly\00048a5c76.jpg  Lilly
2  data/flower_images\Lilly\001ff6644e.jpg  Lilly
3  data/flower_images\Lilly\001ff6656j.jpg  Lilly
4  data/flower_images\Lilly\00973ad1b1.jpg  Lilly
5  data/flower_images\Lilly\00a7d512d6.jpg  Lilly

In [8]:
#shuffle the dataset
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

In [9]:
split_index = len(df) // 1.2
split_index = int(split_index)
df.head()

                                 image_path   label
0   data/flower_images\Lotus\81d74b1184.jpg   Lotus
1  data/flower_images\Orchid\9a3230fab6.jpg  Orchid
2  data/flower_images\Orchid\a792a1c723.jpg  Orchid
3   data/flower_images\Lotus\10012f282d.jpg   Lotus
4   data/flower_images\Lilly\b315379e24.jpg   Lilly

In [10]:
train_df = df[:split_index]
eval_df = df[split_index:]

In [11]:
eval_df.head()

                                    image_path   label
4166  data/flower_images\Orchid\088e4d1c93.jpg  Orchid
4167   data/flower_images\Lotus\3299387701.jpg   Lotus
4168  data/flower_images\Orchid\a2c1c3ecd1.jpg  Orchid
4169   data/flower_images\Tulip\d14e75812f.jpg   Tulip
4170   data/flower_images\Lotus\f57b3b63f2.jpg   Lotus

In [12]:
train_df.to_csv("data/train_set.csv", index=False)
eval_df.to_csv("data/eval_set.csv", index=False)

In [40]:
train_df['label'].unique()

array(['Lotus', 'Orchid', 'Lilly', 'Sunflower', 'Tulip'], dtype=object)